### ISSUE TITLE
Cision PR 

### ISSUE THREAD

**Issue by Cecilialiadmin** [Thorequities/thorequities#1]
Need to change the PR newsfeed company to Cision. 
Call 800-588-3827 for support if needed.

**Comment by timhobert** [comment]
I called Cision/VocusPR. News coverage is not added to the RSS feed automatically. It has to be manually approved. Log in to their system and manually select articles that should go through to the Thor RSS feed. 

URL of feed: https://us.vocuspr.com/Publish/3140335/Thor.xml

@Cecilialiadmin, do  you know what the login is to approve these news items?
