### ISSUE TITLE
Intranet form on thorequities.com website

### ISSUE THREAD

**Issue by Cecilialiadmin** [Thorequities/thorequities#3]

**Comment by timhobert** [comment]
@Cecilialiadmin Does this look OK to you? http://www.thorequities.com/cases

**Comment by Cecilialiadmin** [comment]
Why is it  a pink background?

**Comment by timhobert** [comment]
It was unpublished. I published it. Does it look ok to you now?

**Comment by Cecilialiadmin** [comment]
Better.

Must it have the investor login link?

**Comment by timhobert** [comment]
@Cecilialiadmin OK. It should be working here now: http://www.thorequities.com/cases

**Comment by timhobert** [comment]
Can we close this one out? Is it not working OK here?: http://www.thorequities.com/cases

**Comment by Cecilialiadmin** [comment]
Yes

Regards,

Cecilia A. Li

On May 17, 2016, at 7:03 PM, Tim Hobert <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we close this one out? Is it not working OK here?: http://www.thorequities.com/cases

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/Thorequities/thorequities/issues/3#issuecomment-219879756>

CONFIDENTIALITY NOTICE AND DISCLAIMER

This email and any information contained herein are confidential and may be privileged or otherwise protected from disclosure. If you are not the intended recipient, please notify the sender immediately and delete this message and any attachment from your system. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. For the avoidance of doubt, in no event will this e-mail or any subsequent replies be construed as an enforceable agreement, contract or offer to buy, sell, lease, to amend or terminate any agreement, contract, or lease, to pay any consideration, or to undertake renovations of any property or settle any claim. This e-mail is not an agreement to negotiate. Either party may refuse to agree on any point, cease negotiations, or revise provisions previously agreed. The parties shall not be bound until all necessary parties sign final, definitive and formal agreements, contracts and/or leases reflecting all of the agreed upon terms of the proposed transaction, any consents are obtained making such agreement, contract or lease enforceable and the parties exchange fully executed agreements, contracts or leases.
