### ISSUE TITLE
Portfolio summary pdf not working

### ISSUE THREAD

**Issue by Cecilialiadmin** [Thorequities/thorequities#8]
@timhobert 

The portfolio button on the right is somehow pointing to the wrong file and it also doesn't work. 
I can't find where to edit that. Please help!

Here is the screen shot and the file that needs to be there.

![image](https://cloud.githubusercontent.com/assets/18287993/14744054/f2acd532-0872-11e6-9940-9933221d17fa.png)
[Thor Properties List_April 2016.pdf](https://github.com/Thorequities/thorequities/files/231954/Thor.Properties.List_April.2016.pdf)

**Comment by Cecilialiadmin** [comment]
@timhobert 
Hi Tim, What's the update on this?

**Comment by timhobert** [comment]
I am looking into this issue now.

**Comment by Cecilialiadmin** [comment]
@timhobert, do you have an update on this?

**Comment by timhobert** [comment]
Fixed! Here: ttp://www.thorequities.com/portfolio/list/summary
